### PR TITLE
Id for Drop Cursor

### PR DESCRIPTION
**Pull request by impactvelocity**
Amazing work! It looks like from an issue that you might extend how to use the Drop Cursor, but in the meantime, adding a unique ID so we can override styles with css.

### CODE REVIEW

**Review by impactvelocity — COMMENTED** [review]
Or maybe its better they are className instead of an id? So if someone has multiple Arborists on the same page.

**Comment by impactvelocity** [comment]
Another idea - maybe ability to add classNames from the Tree component for dropCursor wrapper / circle / line then I can could style it with tailwind. :)

**Comment by jameskerr** [comment]
Thanks for this pr @impactvelocity. I think the direction I want to go is passing in a component you want to use to render the drop cursor. That's the pattern we've got going n the library. But since you brought this up, I'll work on something and get a new release out soon. Thanks again! Glad you're getting some use out of the library.

**Comment by impactvelocity** [comment]
Woooo!

**Comment by jameskerr** [comment]
This has been done and is in version 1.2.0: https://github.com/brimdata/react-arborist/releases/tag/v1.2.0

The README has been updated as well to show how to use it. 

Here is an example of the default cursor.
https://github.com/brimdata/react-arborist/blob/main/packages/react-arborist/src/components/default-drop-cursor.tsx

If you're interested in the code changes here is the PR: https://github.com/brimdata/react-arborist/pull/39

**Pull request closed without merging**
