### PR TITLE
Feature/on filter and tree.filtered count

### PR DESCRIPTION
**Pull request by cers**
Attempt at resolving [issue 112](https://github.com/brimdata/react-arborist/issues/112)

### CODE REVIEW

**Review by jameskerr — COMMENTED** [review]
This looks great to me! Althought, to make it more generic, please change the argument that gets passed to onFilter to the list of nodes that were matched.

To get the length from that, you could just call `matches.length`. This will make it more flexible.
```ts
root.tree.onFilter(list)
```

**Comment by cers** [comment]
It occurred to me that this callback is called during render, which means that it cannot be used to directly set state in the parent - do you have any preferred method of solving that? Other than wrapping it in setTimeout?

**Comment by cers** [comment]
Sort of - but visibleNodes also contains parents of matches, not just matches. I'd like an API for telling me the actual (number of) matches. I suppose I can filter outside arborist and update the data in already filtered if I have to instead.

**Comment by jameskerr** [comment]
I'm going to close this for now. We can revisit this when it's time to work on #112

**Pull request closed without merging**
