### PR TITLE
fix: expose item dragIds for DragPreview

### LINKED ISSUE #270: `dragIds` is always empty in `renderDragPreview`
I have a custom `renderDragPreview` component. If I drag a selection, I want it to show the number of dragged items.

My assumption was `dragIds` prop can help with the task. But it's always empty: `[]`.

https://github.com/brimdata/react-arborist/blob/3cee71c318c8cb1c3c490ffa977c1b6d2f0264d2/modules/react-arborist/src/components/drag-preview-container.tsx#L22

### PR DESCRIPTION
**Pull request by qkdreyer**
Fixes #270

### CODE REVIEW

**Comment by qkdreyer** [comment]
See https://github.com/brimdata/react-arborist/commit/f75316f4834864ee0992e46179bdf34da33de4d6#diff-c6218f1b236e78c9be8988bd8b237fef5ad445a0a5e8bddab5edd9f4eb11d0f4L20-L23

**Comment by qkdreyer** [comment]
@jameskerr 👋

**Comment by qkdreyer** [comment]
@jameskerr Could you have a look into this bugfix please?

**Comment by qkdreyer** [comment]
👋

**Comment by jameskerr** [comment]
Seems good to me.

**Comment by goliney** [comment]
@jameskerr Do you know when this fix will be published?

**Comment by jameskerr** [comment]
@goliney This fix has been published in version 3.4.1 yesterday.

**Pull request merged**
