### PR TITLE
Add onDndDrag property to TreeProps and enhance auto-scrolling behavior

### PR DESCRIPTION
**Pull request by percy507**
This PR does two things.

1. Add `onDndDrag` property to `TreeProps`, it is a callback which will be called when a react-dnd drag operation is in progress
2. Enhance auto-scrolling behavior while dragging for the cities demo by using package [`auto-scroll-while-dragging`](https://github.com/percy507/auto-scroll-while-dragging). Before merge this PR, you can try drag one node into a place which far away from its original place by using different browsers (chrome and safari).

### CODE REVIEW

**Comment by percy507** [comment]
One more thing: [auto open folder node while the dragging node on it for the cities demo](https://github.com/brimdata/react-arborist/pull/104/commits/d48f6b4e00b5e12cd9e519f90326659b0de9645e)

**Comment by jameskerr** [comment]
Thank you for this @percy507! I will try it out soon and give a review.

**Comment by jameskerr** [comment]
Thank you for your contribution @percy507, but I'm going to close this PR in favor of a different approach for scrolling while dragging. I'll have to dig into it more, but something like: https://gist.github.com/gaearon/150fa1bed09c92abdb46 might be simple enough.

I think these are valid issues though and I've made tickets for each of them:

Drag and Scroll: https://github.com/brimdata/react-arborist/issues/106

Open Folder on Hover: https://github.com/brimdata/react-arborist/issues/107

**Comment by percy507** [comment]
@jameskerr  Ok. It will be great if there is a better way for scrolling while dragging.

But do you mind to add `onDndDrag` property to `TreeProps`?  (see this commit https://github.com/brimdata/react-arborist/pull/104/commits/d8bae269671452e7d45e46cab593ba280ba0cbac) The property might be useful.

What do you think this commit (https://github.com/brimdata/react-arborist/pull/104/commits/d48f6b4e00b5e12cd9e519f90326659b0de9645e) for #107 issue?

**Pull request closed without merging**
