### PR TITLE
Small updates to the TypeScript types

### PR DESCRIPTION
**Pull request by nvie**
This doesn't change anything about the implementation. It just changes the types to match the current reality a little bit more strictly.

### CODE REVIEW

**Review by jameskerr — APPROVED** [review]
Thank you!

**Comment by jameskerr** [comment]
Looks like the tsc script failed due to the readonly addition. If you remove that, I think the other change is good for this PR.

**Comment by nvie** [comment]
Hey @jameskerr! Thanks for the feedback, I just noticed the tests were not passing, so I made a few more internal annotations to fix those. The benefit of expressing that the `data` you pass won't be mutated by marking it `readonly` on the outside is that you can feed both mutable and readonly arrays to the `Tree` component this way.

In my use case, I found myself writing `<Tree data={[...myReadonlyArray]} />` instead of just `<Tree data={myReadonlyArray} />`.

**Comment by jameskerr** [comment]
Great! That makes sense to me.

**Pull request merged**
