### PR TITLE
Add new tree prop for custom item keys (`itemKey`)

### PR DESCRIPTION
**Pull request by lsfgrd**
Hey, first of all, thanks for the awesome API! 

I'm opening this PR to introduce a new TreeProp: `itemKey`.

While using the library, I had trouble with the following line:

https://github.com/brimdata/react-arborist/blob/fbf0290c7313966ca12b63f887761275ad0f4697/packages/react-arborist/src/components/default-container.tsx#L226

This uses the `id` field by default to generate the React keys for the `react-window` component. It works in the majority of the cases, but it will not work if you happen to have data with the same id (in my case, same item with different parents).

The `itemKey` prop I'm proposing allow us to set our custom logic to build the key, so we can append other data values for example to make it really unique.

### CODE REVIEW

**Comment by jameskerr** [comment]
I see the issue you are having and thanks for contributing a PR!

Can you think of other options that would solve your problem that don't involve adding an additional prop?

**Comment by lsfgrd** [comment]
@jameskerr, thanks for answering!

This is the best approach I could think of. My initial workaround for my use case was using a custom container (using `renderContainer`) to have complete control of the component and avoid the duplicate key issue. Still, it's far too complicated and means maintaining a very similar copy of the default container the library already provides.

I also tried using the `idAccessor` prop to keep my duplicate `id` property from messing up things (creating a different, temporary id, just for the sake of the UI). However, that also complicates the saving data/retrieving data later.

If I can set the key logic myself, it solves the whole issue. It makes sense to me to allow the key to be changed, and the prop was the easiest/more obvious answer. Do you have any specific concerns I'm not seeing?

**Comment by jameskerr** [comment]
Or we could add a method to the node api called "path" which returns an array of its id and all its parents ids. [2, 3, 4]. We could use that as the key. `node.path.join(",")`. We could even add another method called `node.key` which joins the path and returns a string.

**Comment by jameskerr** [comment]
I'm hesitant to add this to the Tree Props because it's adding another public API that will need to be tested and maintained into the future. There are already many props so if we can solve this issue without adding to the public API, I'd be thrilled.

**Pull request closed without merging**
